name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 5.1.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.3
  chewie: ^1.3.6
  collection: ^1.16.0
  contextmenu: ^3.0.0
  dart_vlc: ^0.4.0
  desktop_drop: ^0.4.0
  diacritic: ^0.1.3
  dio: ^4.0.6
  ezanimation: ^0.6.0
  file_picker: ^5.2.3
  file_selector: ^0.9.2+2
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.13
  flutter_portal: ^1.1.2
  flutter_svg: ^1.1.6
  http: ^0.13.5
  http_parser: ^4.0.2
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.6
  jiffy: ^5.0.0
  lottie: ^2.0.0
  meta: ^1.8.0
  path_provider: ^2.0.11
  photo_manager: ^2.5.1+1
  photo_view: ^0.14.0
  rxdart: ^0.27.7
  share_plus: ^6.3.0
  shimmer: ^2.0.0
  stream_chat_flutter_core: ^5.1.0
  synchronized: ^3.0.0+3
  thumblr: ^0.0.4
  url_launcher: ^6.1.7
  video_player: ^2.4.8
  video_player_macos: ^1.0.6
  video_thumbnail: ^0.5.3

flutter:
  assets:
    - images/
    - svgs/
    - lib/svgs/
    - animations/
  uses-material-design: true

dev_dependencies:
  dart_code_metrics: ^4.4.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.13.0
  mocktail: ^0.3.0
  path: ^1.8.2
